# Generated by Django 4.2.6 on 2023-10-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimmer', models.CharField(max_length=100)),
                ('track', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimmer', models.CharField(max_length=100)),
                ('track', models.PositiveIntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('stop_time', models.DateTimeField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
