# Generated by Django 4.2.6 on 2023-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackhistory',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
