# Generated by Django 4.2.6 on 2023-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_trackhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackhistory',
            name='track',
            field=models.PositiveIntegerField(),
        ),
    ]
